version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: forms_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: localhost://root:qwerty@db/forms_db

volumes:
  pgdata:
